name: emergency
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

#dependencies:
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.2
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  get: ^4.6.6
  intl: ^0.19.0
  file_picker: ^8.0.5
  path: ^1.9.0
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  cached_network_image: ^3.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.10

  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true

#all custom added assets:
  assets:
    - assets/images/
    - assets/data/

#all custom added fonts:
  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/Rubik.ttf
          weight: 400

    - family: fira
      fonts:
        - asset: assets/fonts/FiraSans.ttf
          weight: 400

    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
          weight: 400

